// Mock data for shipments
export const mockShipments = [
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=1',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=2',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=3',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=4',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=5',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Closed',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=6',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=7',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=8',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Closed',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=9',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123456',
    shippingName: 'Nike Air Jordan',
    avatar: 'https://i.pravatar.cc/150?img=10',
    skuId: 'WH-0001',
    quantity: '1 Quantity',
    shipmentDate: '26 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123457',
    shippingName: 'Adidas Ultraboost',
    avatar: 'https://i.pravatar.cc/150?img=11',
    skuId: 'WH-0002',
    quantity: '2 Quantity',
    shipmentDate: '25 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123458',
    shippingName: 'Puma Speed',
    avatar: 'https://i.pravatar.cc/150?img=12',
    skuId: 'WH-0003',
    quantity: '1 Quantity',
    shipmentDate: '24 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123459',
    shippingName: 'Reebok Classic',
    avatar: 'https://i.pravatar.cc/150?img=13',
    skuId: 'WH-0004',
    quantity: '3 Quantity',
    shipmentDate: '23 Jun 2025',
    status: 'Closed',
  },
  {
    id: '#123460',
    shippingName: 'New Balance 990',
    avatar: 'https://i.pravatar.cc/150?img=14',
    skuId: 'WH-0005',
    quantity: '1 Quantity',
    shipmentDate: '22 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123461',
    shippingName: 'Converse Chuck',
    avatar: 'https://i.pravatar.cc/150?img=15',
    skuId: 'WH-0006',
    quantity: '2 Quantity',
    shipmentDate: '21 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123462',
    shippingName: 'Vans Old Skool',
    avatar: 'https://i.pravatar.cc/150?img=16',
    skuId: 'WH-0007',
    quantity: '1 Quantity',
    shipmentDate: '20 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123463',
    shippingName: 'Under Armour Curry',
    avatar: 'https://i.pravatar.cc/150?img=17',
    skuId: 'WH-0008',
    quantity: '1 Quantity',
    shipmentDate: '19 Jun 2025',
    status: 'Closed',
  },
  {
    id: '#123464',
    shippingName: 'Asics Gel',
    avatar: 'https://i.pravatar.cc/150?img=18',
    skuId: 'WH-0009',
    quantity: '2 Quantity',
    shipmentDate: '18 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123465',
    shippingName: 'Skechers Go Walk',
    avatar: 'https://i.pravatar.cc/150?img=19',
    skuId: 'WH-0010',
    quantity: '1 Quantity',
    shipmentDate: '17 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123466',
    shippingName: 'Salomon Speedcross',
    avatar: 'https://i.pravatar.cc/150?img=20',
    skuId: 'WH-0011',
    quantity: '1 Quantity',
    shipmentDate: '16 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123467',
    shippingName: 'Hoka One One',
    avatar: 'https://i.pravatar.cc/150?img=21',
    skuId: 'WH-0012',
    quantity: '3 Quantity',
    shipmentDate: '15 Jun 2025',
    status: 'Closed',
  },
  {
    id: '#123468',
    shippingName: 'Brooks Ghost',
    avatar: 'https://i.pravatar.cc/150?img=22',
    skuId: 'WH-0013',
    quantity: '1 Quantity',
    shipmentDate: '14 Jun 2025',
    status: 'Active',
  },
  {
    id: '#123469',
    shippingName: 'Merrell Moab',
    avatar: 'https://i.pravatar.cc/150?img=23',
    skuId: 'WH-0014',
    quantity: '2 Quantity',
    shipmentDate: '13 Jun 2025',
    status: 'Inactive',
  },
  {
    id: '#123470',
    shippingName: 'Timberland Boot',
    avatar: 'https://i.pravatar.cc/150?img=24',
    skuId: 'WH-0015',
    quantity: '1 Quantity',
    shipmentDate: '12 Jun 2025',
    status: 'Active',
  },
];
