FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_DOMAIN
ARG VITE_AUTH0_TENANT_DOMAIN
ARG VITE_AUTH0_AUDIENCE
ARG VITE_CLIENT_ID
ARG VITE_REDIRECT_URI
ARG VITE_TURNSTILE_SITE_KEY
ARG VITE_TURNSTILE_ENABLED
ARG VITE_SOCIAL
ARG VITE_WP_API_URL
ARG VITE_WP_SITE_URL
ARG VITE_USE_S3_UPLOAD
ARG VITE_USE_CLOUDINARY_UPLOAD

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_DOMAIN=$VITE_DOMAIN \
    VITE_AUTH0_TENANT_DOMAIN=$VITE_AUTH0_TENANT_DOMAIN \
    VITE_AUTH0_AUDIENCE=$VITE_AUTH0_AUDIENCE \
    VITE_CLIENT_ID=$VITE_CLIENT_ID \
    VITE_REDIRECT_URI=$VITE_REDIRECT_URI \
    VITE_TURNSTILE_SITE_KEY=$VITE_TURNSTILE_SITE_KEY \
    VITE_TURNSTILE_ENABLED=$VITE_TURNSTILE_ENABLED \
    VITE_SOCIAL=$VITE_SOCIAL \
    VITE_WP_API_URL=$VITE_WP_API_URL \
    VITE_WP_SITE_URL=$VITE_WP_SITE_URL \
    VITE_USE_S3_UPLOAD=$VITE_USE_S3_UPLOAD \
    VITE_USE_CLOUDINARY_UPLOAD=$VITE_USE_CLOUDINARY_UPLOAD

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80
