export const requestItems = [
  {
    id: "req-creator-1",
    type: "creator",
    name: "Sarah Johnson",
    channel: "@sarah_lifestyle",
    email: "sarah.j@gmail.com",
    country: "United Kingdom",
    followers: "125K",
    status: "pending",
    date: "Feb 14, 2025",
  },
  {
    id: "req-creator-2",
    type: "creator",
    name: "Aarav Mehta",
    channel: "@aarav.creates",
    email: "aarav.mehta@gmail.com",
    country: "India",
    followers: "98K",
    status: "approved",
    date: "Feb 11, 2025",
  },
  {
    id: "req-creator-3",
    type: "creator",
    name: "Emma Clarke",
    channel: "@emmaclarke",
    email: "emma.c@gmail.com",
    country: "Canada",
    followers: "76K",
    status: "rejected",
    date: "Feb 09, 2025",
  },
  {
    id: "req-brand-1",
    type: "brand",
    name: "Northwave Studios",
    channel: "@northwave",
    email: "team@northwave.com",
    country: "United States",
    followers: "—",
    status: "pending",
    date: "Feb 13, 2025",
  },
  {
    id: "req-brand-2",
    type: "brand",
    name: "Halo Nutrition",
    channel: "@halonutrition",
    email: "hello@halonutrition.com",
    country: "Australia",
    followers: "—",
    status: "approved",
    date: "Feb 10, 2025",
  },
];

export const requestStatuses = ["all", "pending", "approved", "rejected"];
